version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  reviewers:
  - unhappychoice
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.12.0
    - 1.12.1
  - dependency-name: regexp_parser
    versions:
    - 2.1.0
    - 2.1.1
