version: 2.1

bundle_install: &bundle_install
  run:
    name: bundle install
    command: bundle update --bundler && bundle install --path vendor/bundle --jobs 4

restore_bundle_cache: &restore_bundle_cache
  restore_cache:
    key: cache-bundler-{{ checksum "Gemfile.lock" }}

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - *restore_bundle_cache
      - *bundle_install
      - save_cache:
          key: cache-bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rubocop:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - *restore_bundle_cache
      - *bundle_install
      - run: bundle exec rubocop
  rspec:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - *restore_bundle_cache
      - *bundle_install
      - run: bundle exec rspec
workflows:
  version: 2.1
  rspec:
    jobs:
      - build
      - rubocop
      - rspec
